# Generated by Django 5.1.6 on 2025-03-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halal', '0003_notes_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials_title', models.CharField(max_length=150)),
                ('content', models.FileField(upload_to='training_materials/')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
